name: Test main

on:
  push:
    branches: [main]

jobs:
  call-reusable-workflow:
    uses: wlee221/reusable-workflow-poc/.github/workflows/reusable-workflow-npm.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      # attempt to use a remote reusable workflow without knowing actual NPM_TOKEN value 
      
